name: Build OpenIntegrationEngine Container

on:
  push:
    branches:
      - main
    paths:
      - docker
  pull_request:
    branches:
      - main
    paths:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Container
        working-directory: docker/
        run: ./build-images.sh

      - run: docker image ls